use core::mem::ManuallyDrop;

use register::{mmio::ReadWrite, register_structs};

use crate::memory_map::FUSE;

/// A pointer to the FUSE register block that can be accessed by dereferencing it.
pub const REGISTERS: *const FuseRegion = FUSE as *const FuseRegion;

#[repr(C)]
pub struct FuseRegion {
    /// The generic FUSE registers.
    pub fuse: Registers,
    /// An extnesion to the FUSE chip registers that is only available on Mariko.
    #[cfg(feature = "mariko")]
    pub ext: chip_mariko::MarikoExt,
    #[cfg(not(feature = "mariko"))]
    _reserved: [ReadWrite<u32>; 0x1A],
    /// The FUSE chip registers.
    pub chip: FuseChip,
}

assert_eq_size!(FuseRegion, [u8; 0x400]);

/// Representation of the FUSE chip registers across different platforms.
#[repr(C)]
pub union FuseChip {
    /// The FUSE chip registers that are equal on Erista and Mariko.
    pub common: ManuallyDrop<chip_common::Registers>,
    /// The FUSE chip registers including all Erista-unique registers.
    pub erista: ManuallyDrop<chip_erista::Registers>,
    /// The FUSE chip registers including all Mariko-unique registers.
    #[cfg(feature = "mariko")]
    pub mariko: ManuallyDrop<chip_mariko::Registers>,
}

assert_eq_size!(FuseChip, [u8; 0x300]);

// TODO: Bitfields.

// TODO: Are really all of them ReadWrite?

register_structs! {
    /// Representation of the FUSE registers.
    #[allow(non_snake_case)]
    pub Registers {
        (0x00 => pub FUSE_CTRL: ReadWrite<u32>),
        (0x04 => pub FUSE_ADDR: ReadWrite<u32>),
        (0x08 => pub FUSE_RDATA: ReadWrite<u32>),
        (0x0C => pub FUSE_WDATA: ReadWrite<u32>),
        (0x10 => pub FUSE_TIME_RD1: ReadWrite<u32>),
        (0x14 => pub FUSE_TIME_RD2: ReadWrite<u32>),
        (0x18 => pub FUSE_TIME_PGM1: ReadWrite<u32>),
        (0x1C => pub FUSE_TIME_PGM2: ReadWrite<u32>),
        (0x20 => pub FUSE_PRIV2INTFC: ReadWrite<u32>),
        (0x24 => pub FUSE_FUSEBYPASS: ReadWrite<u32>),
        (0x28 => pub FUSE_PRIVATEKEYDISABLE: ReadWrite<u32>),
        (0x2C => pub FUSE_DISABLEREGPROGRAM: ReadWrite<u32>),
        (0x30 => pub FUSE_WRITE_ACCESS_SW: ReadWrite<u32>),
        (0x34 => pub FUSE_PWR_GOOD_SW: ReadWrite<u32>),
        (0x38 => _reserved0),
        (0x3C => pub FUSE_PRIV2RESHIFT: ReadWrite<u32>),
        (0x40 => _reserved1),
        (0x4C => pub FUSE_TIME_RD3: ReadWrite<u32>),
        (0x50 => _reserved2),
        (0x80 => pub FUSE_PRIVATE_KEY0_NONZERO: ReadWrite<u32>),
        (0x84 => pub FUSE_PRIVATE_KEY1_NONZERO: ReadWrite<u32>),
        (0x88 => pub FUSE_PRIVATE_KEY2_NONZERO: ReadWrite<u32>),
        (0x8C => pub FUSE_PRIVATE_KEY3_NONZERO: ReadWrite<u32>),
        (0x90 => pub FUSE_PRIVATE_KEY4_NONZERO: ReadWrite<u32>),
        (0x94 => _reserved_to_end),
        (0x98 => @END),
    }
}

assert_eq_size!(Registers, [u8; 0x98]);

pub mod chip_common {
    use register::{mmio::ReadWrite, register_structs};

    register_structs! {
        /// Representation of the FUSE chip registers shared between Erista and Mariko.
        #[allow(non_snake_case)]
        pub Registers {
            (0x000 => pub FUSE_PRODUCTION_MODE: ReadWrite<u32>),
            (0x004 => pub FUSE_JTAG_SECUREID_VALID: ReadWrite<u32>),
            (0x008 => pub FUSE_ODM_LOCK: ReadWrite<u32>),
            (0x00C => pub FUSE_OPT_OPENGL_EN: ReadWrite<u32>),
            (0x010 => pub FUSE_SKU_INFO: ReadWrite<u32>),
            (0x014 => pub FUSE_CPU_SPEEDO_0_CALIB: ReadWrite<u32>),
            (0x018 => pub FUSE_CPU_IDDQ_CALIB: ReadWrite<u32>),
            (0x01C => _reserved0),
            (0x028 => pub FUSE_OPT_FT_REV: ReadWrite<u32>),
            (0x02C => pub FUSE_CPU_SPEEDO_1_CALIB: ReadWrite<u32>),
            (0x030 => pub FUSE_CPU_SPEEDO_2_CALIB: ReadWrite<u32>),
            (0x034 => pub FUSE_SOC_SPEEDO_0_CALIB: ReadWrite<u32>),
            (0x038 => pub FUSE_SOC_SPEEDO_1_CALIB: ReadWrite<u32>),
            (0x03C => pub FUSE_SOC_SPEEDO_2_CALIB: ReadWrite<u32>),
            (0x040 => pub FUSE_SOC_IDDQ_CALIB: ReadWrite<u32>),
            (0x044 => _reserved1),
            (0x048 => pub FUSE_FA: ReadWrite<u32>),
            (0x04C => pub FUSE_RESERVED_PRODUCTION: ReadWrite<u32>),
            (0x050 => pub FUSE_HDMI_LANE0_CALIB: ReadWrite<u32>),
            (0x054 => pub FUSE_HDMI_LANE1_CALIB: ReadWrite<u32>),
            (0x058 => pub FUSE_HDMI_LANE2_CALIB: ReadWrite<u32>),
            (0x05C => pub FUSE_HDMI_LANE3_CALIB: ReadWrite<u32>),
            (0x060 => pub FUSE_ENCRYPTION_RATE: ReadWrite<u32>),
            (0x064 => pub FUSE_PUBLIC_KEY: [ReadWrite<u32>; 0x8]),
            (0x084 => pub FUSE_TSENSOR1_CALIB: ReadWrite<u32>),
            (0x088 => pub FUSE_TSENSOR2_CALIB: ReadWrite<u32>),
            (0x08C => _reserved2),
            (0x090 => pub FUSE_OPT_CP_REV: ReadWrite<u32>),
            (0x094 => pub FUSE_OPT_PFG: ReadWrite<u32>),
            (0x098 => pub FUSE_TSENSOR0_CALIB: ReadWrite<u32>),
            (0x09C => pub FUSE_FIRST_BOOTROM_PATCH_SIZE: ReadWrite<u32>),
            (0x0A0 => pub FUSE_SECURITY_MODE: ReadWrite<u32>),
            (0x0A4 => pub FUSE_PRIVATE_KEY: [ReadWrite<u32>; 0x5]),
            (0x0B8 => pub FUSE_ARM_JTAG_DIS: ReadWrite<u32>),
            (0x0BC => pub FUSE_BOOT_DEVICE_INFO: ReadWrite<u32>),
            (0x0C0 => pub FUSE_RESERVED_SW: ReadWrite<u32>),
            (0x0C4 => pub FUSE_OPT_VP9_DISABLE: ReadWrite<u32>),
            (0x0C8 => pub FUSE_RESERVED_ODM_0: [ReadWrite<u32>; 0x8]),
            (0x0E8 => pub FUSE_OBS_DIS: ReadWrite<u32>),
            (0x0EC => _reserved3),
            (0x0F0 => pub FUSE_USB_CALIB: ReadWrite<u32>),
            (0x0F4 => pub FUSE_SKU_DIRECT_CONFIG: ReadWrite<u32>),
            (0x0F8 => pub FUSE_KFUSE_PRIVKEY_CTRL: ReadWrite<u32>),
            (0x0FC => pub FUSE_PACKAGE_INFO: ReadWrite<u32>),
            (0x100 => pub FUSE_OPT_VENDOR_CODE: ReadWrite<u32>),
            (0x104 => pub FUSE_OPT_FAB_CODE: ReadWrite<u32>),
            (0x108 => pub FUSE_OPT_LOT_CODE_0: ReadWrite<u32>),
            (0x10C => pub FUSE_OPT_LOT_CODE_1: ReadWrite<u32>),
            (0x110 => pub FUSE_OPT_WAFER_ID: ReadWrite<u32>),
            (0x114 => pub FUSE_OPT_X_COORDINATE: ReadWrite<u32>),
            (0x118 => pub FUSE_OPT_Y_COORDINATE: ReadWrite<u32>),
            (0x11C => pub FUSE_OPT_SEC_DEBUG_EN: ReadWrite<u32>),
            (0x120 => pub FUSE_OPT_OPS_RESERVED: ReadWrite<u32>),
            (0x124 => _reserved4),
            (0x128 => pub FUSE_GPU_IDDQ_CALIB: ReadWrite<u32>),
            (0x12C => pub FUSE_TSENSOR3_CALIB: ReadWrite<u32>),
            (0x130 => _reserved5),
            (0x144 => pub FUSE_OPT_SAMPLE_TYPE: ReadWrite<u32>),
            (0x148 => pub FUSE_OPT_SUBREVISION: ReadWrite<u32>),
            (0x14C => pub FUSE_OPT_SW_RESERVED_0: ReadWrite<u32>),
            (0x150 => pub FUSE_OPT_SW_RESERVED_1: ReadWrite<u32>),
            (0x154 => pub FUSE_TSENSOR4_CALIB: ReadWrite<u32>),
            (0x158 => pub FUSE_TSENSOR5_CALIB: ReadWrite<u32>),
            (0x15C => pub FUSE_TSENSOR6_CALIB: ReadWrite<u32>),
            (0x160 => pub FUSE_TSENSOR7_CALIB: ReadWrite<u32>),
            (0x164 => pub FUSE_OPT_PRIV_SEC_EN: ReadWrite<u32>),
            (0x168 => _reserved6),
            (0x17C => pub FUSE_FUSE2TSEC_DEBUG_DISABLE: ReadWrite<u32>),
            (0x180 => pub FUSE_TSENSOR_COMMON: ReadWrite<u32>),
            (0x184 => pub FUSE_OPT_CP_BIN: ReadWrite<u32>),
            (0x188 => pub FUSE_OPT_GPU_DISABLE: ReadWrite<u32>),
            (0x18C => pub FUSE_OPT_FT_BIN: ReadWrite<u32>),
            (0x190 => pub FUSE_OPT_DONE_MAP: ReadWrite<u32>),
            (0x194 => _reserved7),
            (0x198 => pub FUSE_APB2JTAG_DISABLE: ReadWrite<u32>),
            (0x19C => pub FUSE_ODM_INFO: ReadWrite<u32>),
            (0x1A0 => _reserved8),
            (0x1A8 => pub FUSE_ARM_CRYPT_DE_FEATURE: ReadWrite<u32>),
            (0x1AC => _reserved9),
            (0x1C0 => pub FUSE_WOA_SKU_FLAG: ReadWrite<u32>),
            (0x1C4 => pub FUSE_ECO_RESERVE_1: ReadWrite<u32>),
            (0x1C8 => pub FUSE_GCPLEX_CONFIG_FUSE: ReadWrite<u32>),
            (0x1CC => pub FUSE_PRODUCTION_MONTH: ReadWrite<u32>),
            (0x1D0 => pub FUSE_RAM_REPAIR_INDICATOR: ReadWrite<u32>),
            (0x1D4 => pub FUSE_TSENSOR9_CALIB: ReadWrite<u32>),
            (0x1D8 => _reserved10),
            (0x1DC => pub FUSE_VMIN_CALIBRATION: ReadWrite<u32>),
            (0x1E0 => pub FUSE_AGING_SENSOR_CALIBRATION: ReadWrite<u32>),
            (0x1E4 => pub FUSE_DEBUG_AUTHENTICATION: ReadWrite<u32>),
            (0x1E8 => pub FUSE_SECURE_PROVISION_INDEX: ReadWrite<u32>),
            (0x1EC => pub FUSE_SECURE_PROVISION_INFO: ReadWrite<u32>),
            (0x1F0 => pub FUSE_OPT_GPU_DISABLE_CP1: ReadWrite<u32>),
            (0x1F4 => pub FUSE_SPARE_ENDIS: ReadWrite<u32>),
            (0x1F8 => pub FUSE_ECO_RESERVE_0: ReadWrite<u32>),
            (0x1FC => _reserved11),
            (0x204 => pub FUSE_RESERVED_CALIB0: ReadWrite<u32>),
            (0x208 => pub FUSE_RESERVED_CALIB1: ReadWrite<u32>),
            (0x20C => pub FUSE_OPT_GPU_TPC0_DISABLE: ReadWrite<u32>),
            (0x210 => pub FUSE_OPT_GPU_TPC0_DISABLE_CP1: ReadWrite<u32>),
            (0x214 => pub FUSE_OPT_CPU_DISABLE: ReadWrite<u32>),
            (0x218 => pub FUSE_OPT_CPU_DISABLE_CP1: ReadWrite<u32>),
            (0x21C => pub FUSE_TSENSOR10_CALIB: ReadWrite<u32>),
            (0x220 => pub FUSE_TSENSOR10_CALIB_AUX: ReadWrite<u32>),
            (0x224 => _reserved12),
            (0x238 => pub FUSE_OPT_GPU_TPC0_DISABLE_CP2: ReadWrite<u32>),
            (0x23C => pub FUSE_OPT_GPU_TPC1_DISABLE: ReadWrite<u32>),
            (0x240 => pub FUSE_OPT_GPU_TPC1_DISABLE_CP1: ReadWrite<u32>),
            (0x244 => pub FUSE_OPT_GPU_TPC1_DISABLE_CP2: ReadWrite<u32>),
            (0x248 => pub FUSE_OPT_CPU_DISABLE_CP2: ReadWrite<u32>),
            (0x24C => pub FUSE_OPT_GPU_DISABLE_CP2: ReadWrite<u32>),
            (0x250 => pub FUSE_USB_CALIB_EXT: ReadWrite<u32>),
            (0x254 => pub FUSE_RESERVED_FIELD: ReadWrite<u32>),
            (0x258 => _reserved13),
            (0x27C => pub FUSE_SPARE_REALIGNMENT_REG: ReadWrite<u32>),
            (0x280 => pub FUSE_SPARE_BIT: [ReadWrite<u32>; 0x20]),
            (0x300 => @END),
        }
    }

    assert_eq_size!(Registers, [u8; 0x300]);
}

pub mod chip_erista {
    use register::{mmio::ReadWrite, register_structs};

    register_structs! {
        /// Representation of the FUSE chip registers for Erista.
        #[allow(non_snake_case)]
        pub Registers {
            (0x000 => pub FUSE_PRODUCTION_MODE: ReadWrite<u32>),
            (0x004 => pub FUSE_JTAG_SECUREID_VALID: ReadWrite<u32>),
            (0x008 => pub FUSE_ODM_LOCK: ReadWrite<u32>),
            (0x00C => pub FUSE_OPT_OPENGL_EN: ReadWrite<u32>),
            (0x010 => pub FUSE_SKU_INFO: ReadWrite<u32>),
            (0x014 => pub FUSE_CPU_SPEEDO_0_CALIB: ReadWrite<u32>),
            (0x018 => pub FUSE_CPU_IDDQ_CALIB: ReadWrite<u32>),
            (0x01C => pub FUSE_DAC_CRT_CALIB: ReadWrite<u32>),
            (0x020 => pub FUSE_DAC_HDTV_CALIB: ReadWrite<u32>),
            (0x024 => pub FUSE_DAC_SDTV_CALIB: ReadWrite<u32>),
            (0x028 => pub FUSE_OPT_FT_REV: ReadWrite<u32>),
            (0x02C => pub FUSE_CPU_SPEEDO_1_CALIB: ReadWrite<u32>),
            (0x030 => pub FUSE_CPU_SPEEDO_2_CALIB: ReadWrite<u32>),
            (0x034 => pub FUSE_SOC_SPEEDO_0_CALIB: ReadWrite<u32>),
            (0x038 => pub FUSE_SOC_SPEEDO_1_CALIB: ReadWrite<u32>),
            (0x03C => pub FUSE_SOC_SPEEDO_2_CALIB: ReadWrite<u32>),
            (0x040 => pub FUSE_SOC_IDDQ_CALIB: ReadWrite<u32>),
            (0x044 => pub FUSE_RESERVED_PRODUCTION_WP: ReadWrite<u32>),
            (0x048 => pub FUSE_FA: ReadWrite<u32>),
            (0x04C => pub FUSE_RESERVED_PRODUCTION: ReadWrite<u32>),
            (0x050 => pub FUSE_HDMI_LANE0_CALIB: ReadWrite<u32>),
            (0x054 => pub FUSE_HDMI_LANE1_CALIB: ReadWrite<u32>),
            (0x058 => pub FUSE_HDMI_LANE2_CALIB: ReadWrite<u32>),
            (0x05C => pub FUSE_HDMI_LANE3_CALIB: ReadWrite<u32>),
            (0x060 => pub FUSE_ENCRYPTION_RATE: ReadWrite<u32>),
            (0x064 => pub FUSE_PUBLIC_KEY: [ReadWrite<u32>; 0x8]),
            (0x084 => pub FUSE_TSENSOR1_CALIB: ReadWrite<u32>),
            (0x088 => pub FUSE_TSENSOR2_CALIB: ReadWrite<u32>),
            (0x08C => pub FUSE_VSENSOR_CALIB: ReadWrite<u32>),
            (0x090 => pub FUSE_OPT_CP_REV: ReadWrite<u32>),
            (0x094 => pub FUSE_OPT_PFG: ReadWrite<u32>),
            (0x098 => pub FUSE_TSENSOR0_CALIB: ReadWrite<u32>),
            (0x09C => pub FUSE_FIRST_BOOTROM_PATCH_SIZE: ReadWrite<u32>),
            (0x0A0 => pub FUSE_SECURITY_MODE: ReadWrite<u32>),
            (0x0A4 => pub FUSE_PRIVATE_KEY: [ReadWrite<u32>; 0x5]),
            (0x0B8 => pub FUSE_ARM_JTAG_DIS: ReadWrite<u32>),
            (0x0BC => pub FUSE_BOOT_DEVICE_INFO: ReadWrite<u32>),
            (0x0C0 => pub FUSE_RESERVED_SW: ReadWrite<u32>),
            (0x0C4 => pub FUSE_OPT_VP9_DISABLE: ReadWrite<u32>),
            (0x0C8 => pub FUSE_RESERVED_ODM_0: [ReadWrite<u32>; 0x8]),
            (0x0E8 => pub FUSE_OBS_DIS: ReadWrite<u32>),
            (0x0EC => pub FUSE_NOR_INFO: ReadWrite<u32>),
            (0x0F0 => pub FUSE_USB_CALIB: ReadWrite<u32>),
            (0x0F4 => pub FUSE_SKU_DIRECT_CONFIG: ReadWrite<u32>),
            (0x0F8 => pub FUSE_KFUSE_PRIVKEY_CTRL: ReadWrite<u32>),
            (0x0FC => pub FUSE_PACKAGE_INFO: ReadWrite<u32>),
            (0x100 => pub FUSE_OPT_VENDOR_CODE: ReadWrite<u32>),
            (0x104 => pub FUSE_OPT_FAB_CODE: ReadWrite<u32>),
            (0x108 => pub FUSE_OPT_LOT_CODE_0: ReadWrite<u32>),
            (0x10C => pub FUSE_OPT_LOT_CODE_1: ReadWrite<u32>),
            (0x110 => pub FUSE_OPT_WAFER_ID: ReadWrite<u32>),
            (0x114 => pub FUSE_OPT_X_COORDINATE: ReadWrite<u32>),
            (0x118 => pub FUSE_OPT_Y_COORDINATE: ReadWrite<u32>),
            (0x11C => pub FUSE_OPT_SEC_DEBUG_EN: ReadWrite<u32>),
            (0x120 => pub FUSE_OPT_OPS_RESERVED: ReadWrite<u32>),
            (0x124 => pub FUSE_SATA_CALIB: ReadWrite<u32>),
            (0x128 => pub FUSE_GPU_IDDQ_CALIB: ReadWrite<u32>),
            (0x12C => pub FUSE_TSENSOR3_CALIB: ReadWrite<u32>),
            (0x130 => pub FUSE_SKU_BOND_OUT_L: ReadWrite<u32>),
            (0x134 => pub FUSE_SKU_BOND_OUT_H: ReadWrite<u32>),
            (0x138 => pub FUSE_SKU_BOND_OUT_U: ReadWrite<u32>),
            (0x13C => pub FUSE_SKU_BOND_OUT_V: ReadWrite<u32>),
            (0x140 => pub FUSE_SKU_BOND_OUT_W: ReadWrite<u32>),
            (0x144 => pub FUSE_OPT_SAMPLE_TYPE: ReadWrite<u32>),
            (0x148 => pub FUSE_OPT_SUBREVISION: ReadWrite<u32>),
            (0x14C => pub FUSE_OPT_SW_RESERVED_0: ReadWrite<u32>),
            (0x150 => pub FUSE_OPT_SW_RESERVED_1: ReadWrite<u32>),
            (0x154 => pub FUSE_TSENSOR4_CALIB: ReadWrite<u32>),
            (0x158 => pub FUSE_TSENSOR5_CALIB: ReadWrite<u32>),
            (0x15C => pub FUSE_TSENSOR6_CALIB: ReadWrite<u32>),
            (0x160 => pub FUSE_TSENSOR7_CALIB: ReadWrite<u32>),
            (0x164 => pub FUSE_OPT_PRIV_SEC_EN: ReadWrite<u32>),
            (0x168 => pub FUSE_PKC_DISABLE: ReadWrite<u32>),
            (0x16C => _reserved0),
            (0x17C => pub FUSE_FUSE2TSEC_DEBUG_DISABLE: ReadWrite<u32>),
            (0x180 => pub FUSE_TSENSOR_COMMON: ReadWrite<u32>),
            (0x184 => pub FUSE_OPT_CP_BIN: ReadWrite<u32>),
            (0x188 => pub FUSE_OPT_GPU_DISABLE: ReadWrite<u32>),
            (0x18C => pub FUSE_OPT_FT_BIN: ReadWrite<u32>),
            (0x190 => pub FUSE_OPT_DONE_MAP: ReadWrite<u32>),
            (0x194 => _reserved1),
            (0x198 => pub FUSE_APB2JTAG_DISABLE: ReadWrite<u32>),
            (0x19C => pub FUSE_ODM_INFO: ReadWrite<u32>),
            (0x1A0 => _reserved2),
            (0x1A8 => pub FUSE_ARM_CRYPT_DE_FEATURE: ReadWrite<u32>),
            (0x1AC => _reserved3),
            (0x1C0 => pub FUSE_WOA_SKU_FLAG: ReadWrite<u32>),
            (0x1C4 => pub FUSE_ECO_RESERVE_1: ReadWrite<u32>),
            (0x1C8 => pub FUSE_GCPLEX_CONFIG_FUSE: ReadWrite<u32>),
            (0x1CC => pub FUSE_PRODUCTION_MONTH: ReadWrite<u32>),
            (0x1D0 => pub FUSE_RAM_REPAIR_INDICATOR: ReadWrite<u32>),
            (0x1D4 => pub FUSE_TSENSOR9_CALIB: ReadWrite<u32>),
            (0x1D8 => _reserved4),
            (0x1DC => pub FUSE_VMIN_CALIBRATION: ReadWrite<u32>),
            (0x1E0 => pub FUSE_AGING_SENSOR_CALIBRATION: ReadWrite<u32>),
            (0x1E4 => pub FUSE_DEBUG_AUTHENTICATION: ReadWrite<u32>),
            (0x1E8 => pub FUSE_SECURE_PROVISION_INDEX: ReadWrite<u32>),
            (0x1EC => pub FUSE_SECURE_PROVISION_INFO: ReadWrite<u32>),
            (0x1F0 => pub FUSE_OPT_GPU_DISABLE_CP1: ReadWrite<u32>),
            (0x1F4 => pub FUSE_SPARE_ENDIS: ReadWrite<u32>),
            (0x1F8 => pub FUSE_ECO_RESERVE_0: ReadWrite<u32>),
            (0x1FC => _reserved5),
            (0x204 => pub FUSE_RESERVED_CALIB0: ReadWrite<u32>),
            (0x208 => pub FUSE_RESERVED_CALIB1: ReadWrite<u32>),
            (0x20C => pub FUSE_OPT_GPU_TPC0_DISABLE: ReadWrite<u32>),
            (0x210 => pub FUSE_OPT_GPU_TPC0_DISABLE_CP1: ReadWrite<u32>),
            (0x214 => pub FUSE_OPT_CPU_DISABLE: ReadWrite<u32>),
            (0x218 => pub FUSE_OPT_CPU_DISABLE_CP1: ReadWrite<u32>),
            (0x21C => pub FUSE_TSENSOR10_CALIB: ReadWrite<u32>),
            (0x220 => pub FUSE_TSENSOR10_CALIB_AUX: ReadWrite<u32>),
            (0x224 => pub FUSE_OPT_RAM_SVOP_DP: ReadWrite<u32>),
            (0x228 => pub FUSE_OPT_RAN_SVOP_PDP: ReadWrite<u32>),
            (0x22C => pub FUSE_OPT_RAM_SVOP_REG: ReadWrite<u32>),
            (0x230 => pub FUSE_OPT_RAM_SVOP_SP: ReadWrite<u32>),
            (0x234 => pub FUSE_OPT_RAM_SVOP_SMPDP: ReadWrite<u32>),
            (0x238 => pub FUSE_OPT_GPU_TPC0_DISABLE_CP2: ReadWrite<u32>),
            (0x23C => pub FUSE_OPT_GPU_TPC1_DISABLE: ReadWrite<u32>),
            (0x240 => pub FUSE_OPT_GPU_TPC1_DISABLE_CP1: ReadWrite<u32>),
            (0x244 => pub FUSE_OPT_GPU_TPC1_DISABLE_CP2: ReadWrite<u32>),
            (0x248 => pub FUSE_OPT_CPU_DISABLE_CP2: ReadWrite<u32>),
            (0x24C => pub FUSE_OPT_GPU_DISABLE_CP2: ReadWrite<u32>),
            (0x250 => pub FUSE_USB_CALIB_EXT: ReadWrite<u32>),
            (0x254 => pub FUSE_RESERVED_FIELD: ReadWrite<u32>),
            (0x258 => pub FUSE_OPT_ECC_EN: ReadWrite<u32>),
            (0x25C => _reserved6),
            (0x27C => pub FUSE_SPARE_REALIGNMENT_REG: ReadWrite<u32>),
            (0x280 => pub FUSE_SPARE_BIT: [ReadWrite<u32>; 0x20]),
            (0x300 => @END),
        }
    }

    assert_eq_size!(Registers, [u8; 0x300]);
}

#[cfg(feature = "mariko")]
pub mod chip_mariko {
    use register::{mmio::ReadWrite, register_structs};

    /// Additional fuse chip registers which are only available on Mariko.
    #[allow(non_snake_case)]
    #[repr(C)]
    pub struct MarikoExt {
        pub FUSE_RESERVED_ODM_8: [ReadWrite<u32>; 14],
        pub FUSE_KEK: [ReadWrite<u32>; 0x4],
        pub FUSE_BEK: [ReadWrite<u32>; 0x4],
        _reserved: [ReadWrite<u32>; 0x4],
    }

    assert_eq_size!(MarikoExt, [u8; 0x68]);

    register_structs! {
        /// Representation of the FUSE chip registers for Mariko.
        #[allow(non_snake_case)]
        pub Registers {
            (0x000 => pub FUSE_PRODUCTION_MODE: ReadWrite<u32>),
            (0x004 => pub FUSE_JTAG_SECUREID_VALID: ReadWrite<u32>),
            (0x008 => pub FUSE_ODM_LOCK: ReadWrite<u32>),
            (0x00C => pub FUSE_OPT_OPENGL_EN: ReadWrite<u32>),
            (0x010 => pub FUSE_SKU_INFO: ReadWrite<u32>),
            (0x014 => pub FUSE_CPU_SPEEDO_0_CALIB: ReadWrite<u32>),
            (0x018 => pub FUSE_CPU_IDDQ_CALIB: ReadWrite<u32>),
            (0x01C => pub FUSE_RESERVED_ODM_22: [ReadWrite<u32>; 0x3]),
            (0x028 => pub FUSE_OPT_FT_REV: ReadWrite<u32>),
            (0x02C => pub FUSE_CPU_SPEEDO_1_CALIB: ReadWrite<u32>),
            (0x030 => pub FUSE_CPU_SPEEDO_2_CALIB: ReadWrite<u32>),
            (0x034 => pub FUSE_SOC_SPEEDO_0_CALIB: ReadWrite<u32>),
            (0x038 => pub FUSE_SOC_SPEEDO_1_CALIB: ReadWrite<u32>),
            (0x03C => pub FUSE_SOC_SPEEDO_2_CALIB: ReadWrite<u32>),
            (0x040 => pub FUSE_SOC_IDDQ_CALIB: ReadWrite<u32>),
            (0x044 => pub FUSE_RESERVED_ODM_25: [ReadWrite<u32>; 0x1]),
            (0x048 => pub FUSE_FA: ReadWrite<u32>),
            (0x04C => pub FUSE_RESERVED_PRODUCTION: ReadWrite<u32>),
            (0x050 => pub FUSE_HDMI_LANE0_CALIB: ReadWrite<u32>),
            (0x054 => pub FUSE_HDMI_LANE1_CALIB: ReadWrite<u32>),
            (0x058 => pub FUSE_HDMI_LANE2_CALIB: ReadWrite<u32>),
            (0x05C => pub FUSE_HDMI_LANE3_CALIB: ReadWrite<u32>),
            (0x060 => pub FUSE_ENCRYPTION_RATE: ReadWrite<u32>),
            (0x064 => pub FUSE_PUBLIC_KEY: [ReadWrite<u32>; 0x8]),
            (0x084 => pub FUSE_TSENSOR1_CALIB: ReadWrite<u32>),
            (0x088 => pub FUSE_TSENSOR2_CALIB: ReadWrite<u32>),
            (0x08C => pub FUSE_OPT_SECURE_SCC_DIS: ReadWrite<u32>),
            (0x090 => pub FUSE_OPT_CP_REV: ReadWrite<u32>),
            (0x094 => pub FUSE_OPT_PFG: ReadWrite<u32>),
            (0x098 => pub FUSE_TSENSOR0_CALIB: ReadWrite<u32>),
            (0x09C => pub FUSE_FIRST_BOOTROM_PATCH_SIZE: ReadWrite<u32>),
            (0x0A0 => pub FUSE_SECURITY_MODE: ReadWrite<u32>),
            (0x0A4 => pub FUSE_PRIVATE_KEY: [ReadWrite<u32>; 0x5]),
            (0x0B8 => pub FUSE_ARM_JTAG_DIS: ReadWrite<u32>),
            (0x0BC => pub FUSE_BOOT_DEVICE_INFO: ReadWrite<u32>),
            (0x0C0 => pub FUSE_RESERVED_SW: ReadWrite<u32>),
            (0x0C4 => pub FUSE_OPT_VP9_DISABLE: ReadWrite<u32>),
            (0x0C8 => pub FUSE_RESERVED_ODM_0: [ReadWrite<u32>; 0x8]),
            (0x0E8 => pub FUSE_OBS_DIS: ReadWrite<u32>),
            (0x0EC => _reserved0),
            (0x0F0 => pub FUSE_USB_CALIB: ReadWrite<u32>),
            (0x0F4 => pub FUSE_SKU_DIRECT_CONFIG: ReadWrite<u32>),
            (0x0F8 => pub FUSE_KFUSE_PRIVKEY_CTRL: ReadWrite<u32>),
            (0x0FC => pub FUSE_PACKAGE_INFO: ReadWrite<u32>),
            (0x100 => pub FUSE_OPT_VENDOR_CODE: ReadWrite<u32>),
            (0x104 => pub FUSE_OPT_FAB_CODE: ReadWrite<u32>),
            (0x108 => pub FUSE_OPT_LOT_CODE_0: ReadWrite<u32>),
            (0x10C => pub FUSE_OPT_LOT_CODE_1: ReadWrite<u32>),
            (0x110 => pub FUSE_OPT_WAFER_ID: ReadWrite<u32>),
            (0x114 => pub FUSE_OPT_X_COORDINATE: ReadWrite<u32>),
            (0x118 => pub FUSE_OPT_Y_COORDINATE: ReadWrite<u32>),
            (0x11C => pub FUSE_OPT_SEC_DEBUG_EN: ReadWrite<u32>),
            (0x120 => pub FUSE_OPT_OPS_RESERVED: ReadWrite<u32>),
            (0x124 => _reserved1),
            (0x128 => pub FUSE_GPU_IDDQ_CALIB: ReadWrite<u32>),
            (0x12C => pub FUSE_TSENSOR3_CALIB: ReadWrite<u32>),
            (0x130 => pub FUSE_CLOCK_BONDOUT0: ReadWrite<u32>),
            (0x134 => pub FUSE_CLOCK_BONDOUT1: ReadWrite<u32>),
            (0x138 => pub FUSE_RESERVED_ODM_26: [ReadWrite<u32>; 0x3]),
            (0x144 => pub FUSE_OPT_SAMPLE_TYPE: ReadWrite<u32>),
            (0x148 => pub FUSE_OPT_SUBREVISION: ReadWrite<u32>),
            (0x14C => pub FUSE_OPT_SW_RESERVED_0: ReadWrite<u32>),
            (0x150 => pub FUSE_OPT_SW_RESERVED_1: ReadWrite<u32>),
            (0x154 => pub FUSE_TSENSOR4_CALIB: ReadWrite<u32>),
            (0x158 => pub FUSE_TSENSOR5_CALIB: ReadWrite<u32>),
            (0x15C => pub FUSE_TSENSOR6_CALIB: ReadWrite<u32>),
            (0x160 => pub FUSE_TSENSOR7_CALIB: ReadWrite<u32>),
            (0x164 => pub FUSE_OPT_PRIV_SEC_EN: ReadWrite<u32>),
            (0x168 => pub FUSE_BOOT_SECURITY_INFO: ReadWrite<u32>),
            (0x16C => _reserved2),
            (0x17C => pub FUSE_FUSE2TSEC_DEBUG_DISABLE: ReadWrite<u32>),
            (0x180 => pub FUSE_TSENSOR_COMMON: ReadWrite<u32>),
            (0x184 => pub FUSE_OPT_CP_BIN: ReadWrite<u32>),
            (0x188 => pub FUSE_OPT_GPU_DISABLE: ReadWrite<u32>),
            (0x18C => pub FUSE_OPT_FT_BIN: ReadWrite<u32>),
            (0x190 => pub FUSE_OPT_DONE_MAP: ReadWrite<u32>),
            (0x194 => pub FUSE_RESERVED_ODM_29: [ReadWrite<u32>; 0x1]),
            (0x198 => pub FUSE_APB2JTAG_DISABLE: ReadWrite<u32>),
            (0x19C => pub FUSE_ODM_INFO: ReadWrite<u32>),
            (0x1A0 => _reserved3),
            (0x1A8 => pub FUSE_ARM_CRYPT_DE_FEATURE: ReadWrite<u32>),
            (0x1AC => _reserved4),
            (0x1C0 => pub FUSE_WOA_SKU_FLAG: ReadWrite<u32>),
            (0x1C4 => pub FUSE_ECO_RESERVE_1: ReadWrite<u32>),
            (0x1C8 => pub FUSE_GCPLEX_CONFIG_FUSE: ReadWrite<u32>),
            (0x1CC => pub FUSE_PRODUCTION_MONTH: ReadWrite<u32>),
            (0x1D0 => pub FUSE_RAM_REPAIR_INDICATOR: ReadWrite<u32>),
            (0x1D4 => pub FUSE_TSENSOR9_CALIB: ReadWrite<u32>),
            (0x1D8 => _reserved5),
            (0x1DC => pub FUSE_VMIN_CALIBRATION: ReadWrite<u32>),
            (0x1E0 => pub FUSE_AGING_SENSOR_CALIBRATION: ReadWrite<u32>),
            (0x1E4 => pub FUSE_DEBUG_AUTHENTICATION: ReadWrite<u32>),
            (0x1E8 => pub FUSE_SECURE_PROVISION_INDEX: ReadWrite<u32>),
            (0x1EC => pub FUSE_SECURE_PROVISION_INFO: ReadWrite<u32>),
            (0x1F0 => pub FUSE_OPT_GPU_DISABLE_CP1: ReadWrite<u32>),
            (0x1F4 => pub FUSE_SPARE_ENDIS: ReadWrite<u32>),
            (0x1F8 => pub FUSE_ECO_RESERVE_0: ReadWrite<u32>),
            (0x1FC => _reserved6),
            (0x204 => pub FUSE_RESERVED_CALIB0: ReadWrite<u32>),
            (0x208 => pub FUSE_RESERVED_CALIB1: ReadWrite<u32>),
            (0x20C => pub FUSE_OPT_GPU_TPC0_DISABLE: ReadWrite<u32>),
            (0x210 => pub FUSE_OPT_GPU_TPC0_DISABLE_CP1: ReadWrite<u32>),
            (0x214 => pub FUSE_OPT_CPU_DISABLE: ReadWrite<u32>),
            (0x218 => pub FUSE_OPT_CPU_DISABLE_CP1: ReadWrite<u32>),
            (0x21C => pub FUSE_TSENSOR10_CALIB: ReadWrite<u32>),
            (0x220 => pub FUSE_TSENSOR10_CALIB_AUX: ReadWrite<u32>),
            (0x224 => _reserved7),
            (0x238 => pub FUSE_OPT_GPU_TPC0_DISABLE_CP2: ReadWrite<u32>),
            (0x23C => pub FUSE_OPT_GPU_TPC1_DISABLE: ReadWrite<u32>),
            (0x240 => pub FUSE_OPT_GPU_TPC1_DISABLE_CP1: ReadWrite<u32>),
            (0x244 => pub FUSE_OPT_GPU_TPC1_DISABLE_CP2: ReadWrite<u32>),
            (0x248 => pub FUSE_OPT_CPU_DISABLE_CP2: ReadWrite<u32>),
            (0x24C => pub FUSE_OPT_GPU_DISABLE_CP2: ReadWrite<u32>),
            (0x250 => pub FUSE_USB_CALIB_EXT: ReadWrite<u32>),
            (0x254 => pub FUSE_RESERVED_FIELD: ReadWrite<u32>),
            (0x258 => _reserved8),
            (0x27C => pub FUSE_SPARE_REALIGNMENT_REG: ReadWrite<u32>),
            (0x280 => pub FUSE_SPARE_BIT: [ReadWrite<u32>; 0x20]),
            (0x300 => @END),
        }
    }

    assert_eq_size!(Registers, [u8; 0x300]);
}
